### ISSUE TITLE
Code Review Checklist

### ISSUE THREAD

**Issue by lucashsmoraes** [lucashsmoraes/validateProperties#14]
## Checklist de Revisão de Código
- [ ] Código formatado corretamente
- [ ] Todos os testes passam
- [ ] Documentação atualizada
- [ ] Código revisado por outro desenvolvedor
