### ISSUE TITLE
Code Review Checklist

### ISSUE THREAD

**Issue by lucashsmoraes** [lucashsmoraes/validateProperties#21]
## Checklist de Revisão de Código
- [x] Código formatado corretamente
- [x] Todos os testes passam
- [x] Documentação atualizada
- [x] Código revisado por outro desenvolvedor
